sudo: required
dist: xenial
# Force travis to use its minimal image with default Python settings
language: python
python:
  - "3.6"
compiler:
  - gcc

env:
  global:
    - IMAGE=hello-world
    - GIT_REPO=~/ipa-mae-ma/safety-drl

install:
  - sudo apt-get install tree
  - wget https://repo.continuum.io/miniconda/Miniconda3-3.7.0-Linux-x86_64.sh -O ~/miniconda.sh
  - bash ~/miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda env create -f environment.yaml
  - conda activate safety
  - pip install pytest

before_script:
  - echo 'Hello Travis CI before script'

script:
  - pytest

deploy:
  provider: releases
  api_key:
  file:
  skip_cleanup: true
  on:
    tags: true
