name: safety
channels:
  - conda-forge
  - cogsci
dependencies:
    - python>=3.5
    - click
    - numpy
    - tensorflow-gpu==1.9
    - pandas
    - matplotlib
    - h5py
    - pytest
    - tqdm
    - pip:
        - gym==0.9.2
        - pygame
        - pyyaml
