name: safety
channels:
  - conda-forge
  - cogsci
dependencies:
    - python>=3.5
    - ipython
    - click
    - numpy
    - tensorflow>=1.11
    - Theano
    - pandas
    - matplotlib
    - h5py
    - pytest
    - yaml
    - tqdm
    - pip:
        - gym==0.9.2
        - pygame
        - keras==1.2
