epochs: [5, 10, 20]
learning_rate: [0.001, 0.01, 0.1]
complex: [true, false]
init_method: [he_uniform, glorot_uniform]
optimizer: [Adam, RMSProp]
simple: [5, 10, 50, 100, 250]
number_of_experiments: [50]
steps: [300, 1000]
