################################
# DQN from 'Human-level control through deep reinforcement learning' by Mnih et al. 2015
################################
minibatch_size: 32
# DQN size
# replay_memory_size: 1.0e6
# HRA size
replay_memory_size: 10000
# gamma: 0.99
# gamma from HRA
gamma: 0.85
# gamma: 0.75

################################
# RMSprop
################################
learning_rate: 0.000025
# learning_rate: 0.00025
# learning_rate: 2.5e-7
# lr from HRA
# learning_rate: 0.0005
# learning_rate: 0.001
gradient_momentum: 0.95
squared_gradient_momentum: 0.95
min_squared_gradient: 0.01

################################
# epsilon greedy
################################
annealing: True
epsilon: 1.0
epsilon_min: 0.1
eps_max_frame: 100000


################################
# training
################################
num_epochs: 50
num_episodes: 100
num_steps: 300
target_network_update_frequency: 500

random_seed: 1234
action_dim: 4
num_units: 250

dqn:
  gamma: 0.85
  learning_rate: 0.0005
  use_hra: False
dqn_1:
  gamma: 0.85
  learning_rate: 0.0005
  use_hra: False
hra: 
  gamma: 0.99
  learning_rate: 0.001
  use_hra: True
hra_1:
  gamma: 0.99
  learning_rate: 0.001
  use_hra: True