################################
# DQN from 'Human-level control through deep reinforcement learning' by Mnih et al. 2015
################################
minibatch_size: 32
replay_memory_size: 10000
gamma: 0.99

################################
# RMSprop
################################
learning_rate: 0.0005
gradient_momentum: 0.95
squared_gradient_momentum: 0.95
min_squared_gradient: 0.01

################################
# epsilon greedy
################################
annealing: True
epsilon: 1.0
epsilon_min: 0.1
eps_max_frame: 100000


################################
# training
################################
num_epochs: 5
num_episodes: 100
num_steps: 300
target_network_update_frequency: 500

random_seed: 1234
action_dim: 4
num_units: 250


mini:
  ################################
  minibatch_size: 32
  # replay buffer size
  # DQN size 1.0e6
  # HRA size: 10000
  replay_memory_size: 10000
  # gamma from HRA: 0.85
  gamma: 0.85
  ################################
  learning_rate: 0.000025
  # lr from HRA: 0.0005
  gradient_momentum: 0.95
  squared_gradient_momentum: 0.95
  min_squared_gradient: 0.01
  ################################
  annealing: True
  epsilon: 1.0
  epsilon_min: 0.1
  eps_max_frame: 100000
  ################################
  num_epochs: 5
  num_episodes: 100
  num_steps: 300
  target_network_update_frequency: 500
  random_seed: 1234

small:
  ################################
  minibatch_size: 32
  # replay buffer size
  # DQN size 1.0e6
  # HRA size: 10000
  replay_memory_size: 20000
  # gamma from HRA: 0.85
  gamma: 0.85
  ################################
  learning_rate: 0.0005
  # lr from HRA: 0.0005
  gradient_momentum: 0.95
  squared_gradient_momentum: 0.95
  min_squared_gradient: 0.01
  ################################
  annealing: True
  epsilon: 1.0
  epsilon_min: 0.1
  eps_max_frame: 150000
  ################################
  num_epochs: 5
  num_episodes: 100
  num_steps: 500
  target_network_update_frequency: 500
  random_seed: 1234


dqn_1:
  gamma: 0.85
  learning_rate: 0.0005
  use_hra: False
hra: 
  gamma: 0.99
  learning_rate: 0.001
  use_hra: True
hra_1:
  gamma: 0.99
  learning_rate: 0.001
  use_hra: True