################################
# A3C from 'Asynchronous Methods for Deep Reinforcement Learning' by Mnih et al. 2016
################################
minibatch_size: 32
replay_memory_size: 10000
gamma: 0.99

################################
# Asynchronous
################################
threads: 8
optimizers: 2
thread_delay: 0.001
n_step_return: 8
loss_value_coefficient: 0.5
loss_entropy_coefficient: 0.01

################################
# RMSprop
################################
learning_rate: 0.005
gradient_momentum: 0.95
squared_gradient_momentum: 0.95
min_squared_gradient: 0.01

################################
# epsilon greedy
################################
epsilon: 1.0
epsilon_min: 0.1
eps_max_frame: 100000

################################
# training
################################
num_epochs: 5
num_episodes: 100
num_steps: 300
target_network_update_frequency: 500

random_seed: 1234
action_dim: 4
num_units: 250


mini:
  ################################
  minibatch_size: 32
  replay_memory_size: 10000
  gamma: 0.99
  ################################
  threads: 1
  n_step_return: 8
  loss_value_coefficient: 0.5
  loss_entropy_coefficient: 0.01
  ################################
  learning_rate: 0.00001
  gradient_momentum: 0.95
  squared_gradient_momentum: 0.95
  min_squared_gradient: 0.01
  ################################
  annealing: True
  epsilon: 1.0
  epsilon_min: 0.1
  eps_max_frame: 100000
  ################################
  num_epochs: 5
  num_episodes: 100
  num_steps: 300
  target_network_update_frequency: 500
  random_seed: 1234

small:
  ################################
  minibatch_size: 32
  replay_memory_size: 10000
  gamma: 0.85
  ################################
  threads: 8
  n_step_return: 8
  loss_value_coefficient: 0.5
  loss_entropy_coefficient: 0.01
  ################################
  learning_rate: 0.005
  gradient_momentum: 0.95
  squared_gradient_momentum: 0.95
  min_squared_gradient: 0.01
  ################################
  annealing: True
  epsilon: 1.0
  epsilon_min: 0.1
  eps_max_frame: 100000
  ################################
  num_epochs: 5
  num_episodes: 100
  num_steps: 300
  target_network_update_frequency: 500
  random_seed: 1234
