################################
# A3C from 'Asynchronous Methods for Deep Reinforcement Learning' by Mnih et al. 2016
################################
minibatch_size: 32
gamma: 0.99
replay_memory_size: 100
update_frequency: 50
################################
# RMSprop
################################
learning_rate: 0.005

################################
# epsilon greedy
################################
epsilon: 1.0
epsilon_min: 0.1
eps_max_frame: 100000

################################
# training
################################
num_epochs: 5
num_episodes: 100
num_steps: 300

random_seed: 1234
action_dim: 4
num_units: 250


mini:
  ################################
  minibatch_size: 32
  gamma: 0.99
  replay_memory_size: 10000
  update_frequency: 100
  ################################
  # FIXME: use lower learning rate
  learning_rate: 0.001
  ################################
  epsilon: 0.9
  epsilon_min: 0.01
  eps_max_frame: 100000
  ################################
  num_epochs: 10
  num_episodes: 100
  num_steps: 300
  random_seed: 12
  # random_seed: 1234

small:
  ################################
  minibatch_size: 32
  gamma: 0.85
  replay_memory_size: 10000
  update_frequency: 50
  ################################
  learning_rate: 0.005
  ################################
  epsilon: 1.0
  epsilon_min: 0.1
  eps_max_frame: 100000
  ################################
  num_epochs: 5
  num_episodes: 100
  num_steps: 300
  random_seed: 1234
